customhost = "employee.coyyrl80apms.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "teeboonchong-employee"
customregion = "us-east-1"
